#!/usr/bin/env bash

echo "Values of Macros:"
echo "TEMPLATE_TODAY: $TEMPLATE_TODAY"
echo "TEMPLATE_YESTERDAY: $TEMPLATE_YESTERDAY"
echo "TEMPLATE_LAST_MONTH: $TEMPLATE_LAST_MONTH"
echo "TEMPLATE_LAST_MONTH_V2: $TEMPLATE_LAST_MONTH_V2"
echo "TEMPLATE_TWO_MONTHS_AGO: $TEMPLATE_TWO_MONTHS_AGO"